[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "check_mqtt_topic_age"
authors = [
    {name = "Thomas Wagner", email = "wagner-thomas@gmx.at"},
]
description = "Nagios/Icinga plugin checking when messages last arrived on MQTT topics, and the daemon logging them"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "GPL-2.0-or-later"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: System :: Monitoring",
]
dependencies = [
    "paho-mqtt>=1.5",
]
dynamic = ["version"]

[project.urls]
repository = 'https://github.com/Aikhjarto/check_mqtt_topic_age'

[project.scripts]
check_mqtt_topic_age = "check_mqtt_topic_age.check_mqtt_topic_age:main"
mqtt_message_timestamp_logger = "mqtt_message_timestamp_logger.mqtt_message_timestamp_logger:main"

[tool.setuptools.dynamic]
version = {attr = "check_mqtt_topic_age.check_mqtt_topic_age.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
